### ISSUE TITLE
使用vercel一键部署之后，主要功能无法使用

### ISSUE THREAD

**Issue by KasenRi** [hellovigoss/ChatGIF#1]
搜图功能无法使用
输入内容回车之后显示：Ops~ Something went wrong, please try again later!
但是同api在本地的其他服务调用可以正常返回
是因为openAI把github地址屏蔽的原因吗？
我看到源码里好像对api做了一层代理
但是示例网站又很顺畅
希望能得到帮助

**Comment by KasenRi** [comment]
补充一下，第一次使用是正常的，然后就使用不了

**Comment by hellovigoss** [comment]
感谢反馈。
代理是部署用于直连openai的api的，也可以修改代码直接连接openai的域名。
另外：如果在本地部署，请参考```.env.local.example```建立```.env.local```文件并正确填写apikey

**Comment by hellovigoss** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/590771/231765678-7251c563-52e8-4ee3-866c-c87b8ef35b38.png">
最新版本已经支持自定义，可以留空```OPENAI_PROXY```直连openai 官方api

**Comment by KasenRi** [comment]
感谢回复，本地部署十分稳定
